guardian/newswires

cdk/lib/__snapshots__/wires-feeds.test.ts.snap, cdk/lib/wires-feeds.ts, docker-compose.yml, ingestion-lambda/package.json, ingestion-lambda/src/config.ts, ingestion-lambda/src/handler.ts, ingestion-lambda/src/s3.ts, localstack/README.md, localstack/resources.sh, package-lock.json
- Create an S3 bucket
- Trigger the `ingestion-lambda` on events from the incoming fingerpost SQS queue
- Store the incoming feed data in S3
=> Ingest incoming wires from SQS to S3

cdk/lib/__snapshots__/wires-feeds.test.ts.snap, cdk/lib/constructs/database.ts, cdk/lib/wires-feeds.ts
Extracts just the database CDK from #4 to get it into main ASAP
=> Add newswires database

README.md, newswires/app/AppComponents.scala, newswires/app/conf/Database.scala, newswires/app/controllers/ManagementController.scala, newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostMessage.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/build.sbt, newswires/client/index.html, newswires/client/package-lock.json, newswires/client/package.json, newswires/client/src/App.css, newswires/client/src/App.tsx, newswires/client/src/index.css, newswires/conf/routes, newswires/scripts/setup
Set up the server with the ability and config to connect to the database with IAM auth. When running locally you can connect to the CODE db with an `ssm ssh` tunnel. There's currently no way to connect it to a local postgres, we'll need to figure out some way to switch between local<->local, and local<->CODE, but that's for the future.
Instructions for running with tunnel in the README.
=> server connects to DB with IAM auth

ingestion-lambda/localRun.ts
=> set timestamp in schema to include time zone

newswires/app/controllers/QueryController.scala, newswires/app/controllers/ViteController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/client/package-lock.json, newswires/client/package.json, newswires/client/src/App.tsx, newswires/client/src/Item.tsx, newswires/client/src/WireDetail.tsx, newswires/client/src/WiresCards.tsx, newswires/client/src/sharedTypes.ts, newswires/client/src/urlState.tsx, newswires/conf/routes
API and view for specific wire item. We'll probably want to tweak design and layout, and definitely need to think about the navigation story (how we get to and from this view) but this feels like a sensible starting point.
- [Add api/item/*id lookup endpoint](https://github.com/guardian/newswires/pull/23/commits/ac137acea8e315059b99d0a5da3fe03db65a8b8e)
- [Add basic '/item/' route](https://github.com/guardian/newswires/pull/23/commits/ef64a749945f7cc442f37459a372421daed52ef9)
- [Extract WireDetail component (prep for Item page)](https://github.com/guardian/newswires/pull/23/commits/25b1c2ebfdb72a377f08224888ca25dfd2fb871b)
- [Add zod for WireData type](https://github.com/guardian/newswires/pull/23/commits/09cddd829cedea7b8e838ea7081fa06d1e018f02)
- [Add content to Item …
=> Add specific item view

newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/WireDetail.tsx, newswires/client/src/sharedTypes.ts
also do some field renaming to make life easier
There's more subfields on the wires data coming through now; parse and surface the most interesting of these in the API.
There are more still to discover and interrogate, but I'm less certain that these will contain interesting values for us.
Deploy to CODE and check API responses.
=> add some more fields into the FingerpostWire case class

newswires/client/src/Item.tsx, newswires/client/src/WireDetail.tsx
=> add button to show JSON

newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/sharedTypes.ts
…until we denormalise keywords
=> [temp] comment out keywords aggregation logic in search responses as it's painfully slow

newswires/client/src/urlState.ts, newswires/client/src/useSearch.tsx
=> If we're refreshing data, pass 'sinceId'

ingestion-lambda/src/handler.ts
When the ingestion lambda receives an item from the SQS queue, don't try to write it to the db unless there's the `Message-Id` attribute on the item, to use as an `external_id`. 
Instead:
- Write the item data to S3
- Throw an error
The error will be caught, meaning that the record will be failed, and the reason will be logged. The record will get retried and will almost certainly fail again, but after a couple of tries it'll go into the DLQ.
We should probably tighten up the error handling at some point so that we don't needlessly retry these records, but this feels like a step in the right direction at the moment, and I suggest that we revisit this when we add more validation to the incoming items, within the ingestion lambda. …
=> Don't write items with no external id to db

.gitignore
We don't want it in version control.
=> .gitignore `.DS_Store`

README.md, scripts/check-requirements, scripts/setup, scripts/start
- Move `setup` script to the root of the project.
- Pull the 'check requirements' functionality into a separate script, and run it as part of both `setup` and `start`.
- Update the root README to reflect the new setup process.
=> Update setup script and instructions

newswires/client/src/App.tsx
Add a home link to clear any filters.
=> Newswires UI: add home link

newswires/app/controllers/QueryController.scala, newswires/client/package-lock.json, newswires/client/package.json, newswires/client/src/SideNav.tsx, newswires/client/src/WireDetail.tsx, newswires/client/src/sharedTypes.ts, newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts, newswires/conf/routes
Filter search by clicking on subject badges in the Wire details panel.
=> Newswires UI: filter search by subject

newswires/client/src/context/SearchContext.tsx, newswires/client/src/context/fetchResults.ts
Uses an AbortController to abort search requests (and auto-refresh requests) if a new search has been triggered since, and the original request hasn't resolved yet.
=> Add AbortController to searches, to abort requests when terms are updated

.github/workflows/ci.yaml, package-lock.json, package.json
Update Github actions config and workspace in package.json to include the cleanup-lambda.
=> Cleanup Lambda: fix CI integration

db/migrations/V10__ingested_at_index.sql
Add index to ingested_at column.
=> DB: add index for ingested_at column

newswires/app/db/FingerpostWireEntry.scala
Count total records in separate query:
- The count query running separately; it does not force PostgreSQL to scan all matching rows for each result.
- The data query executes faster because it no longer calculates COUNT(*) OVER() for every row.
Run: `EXPLAIN ANALYZE <query>`
```
explain analyze SELECT COUNT(*) OVER() AS total_count, 
fm.id as i_on_fm,
fm.external_id as ei_on_fm,
fm.ingested_at as ia_on_fm,
fm.supplier as s_on_fm,
fm.content as c_on_fm
, ts_headline('english', fm.content->>'body_text', websearch_to_tsquery('english', 'london')) AS h_on_fm
FROM fingerpost_wire_entry fm
WHERE websearch_to_tsquery('english', 'london') @@ fm.combined_textsearch
ORDER BY fm.ingested_at DESC
LIMIT 30;
QUERY PLAN …
```
=> Newswires backend: improve search performance

db/flyway.sc, db/migrations/V13__category_codes_column.sql
We have a PROD stack now, so we need to support migrations for it.
=> Remote connection can be for CODE or PROD

newswires/client/.eslintrc.cjs, newswires/client/.gitignore, newswires/client/.storybook/main.ts, newswires/client/.storybook/preview.ts, newswires/client/package.json, newswires/client/src/SearchBox.stories.tsx, newswires/client/src/icons.ts, package-lock.json, package.json
- Add storybook, [via their `create` helper](https://storybook.js.org/docs#install-storybook).
- Add a simple proof-of-concept story for the `SearchBox` component.
- Easier to document and inspect expected component behaviour when developing.
- Extra dependencies, can be a pain. I think I'll find it useful for some upcoming feature development, but am open to the idea of either not adding it, or removing it later if it feels like an unnecessary maintenance burden. …
=> Initial storybook setup

newswires/app/conf/SearchBuckets.scala, newswires/client/src/SideNav.tsx
=> make a bucket that combines all world buckets

ingestion-lambda/src/handler.test.ts, ingestion-lambda/src/handler.ts
…ters
Decode stories text body to remove escaped characters.
=> Newswires ingestion: decode stories text body to remove escaped characters

.husky/pre-commit, newswires/client/src/context/SearchContext.test.tsx, newswires/client/src/dateHelpers.test.ts, newswires/client/src/tests/testHelpers.ts, newswires/client/src/urlState.test.ts, package-lock.json, package.json, poller-lambdas/src/pollers/ap/apPoller.test.ts
Add pre-commit hook to save time when linting issues and failed unit tests are missed.
=> Newswires UI commit hooks

newswires/client/src/Item.stories.tsx, newswires/client/src/Item.tsx, newswires/client/src/ItemData.tsx
A story details action buttons:
- Update the close button to display a cross instead of an arrow
- Move close button to the right
- Add two buttons to navigate stories as an alternative to using keyboard shortcuts
=> Newswires UI: add story details action buttons

newswires/app/controllers/PermissionsCheck.scala
Start checking user's permissions for access to newswires.
=> start checking wires access permission for access to newswires

ingestion-lambda/src/categoryCodes.test.ts, ingestion-lambda/src/handler.ts
- Add story headline and abstract to content when processing category codes to better infer the region code
- Filter out empty category codes
=> Ingestion: update minor agencies world

ingestion-lambda/src/handler.ts, newswires/app/conf/SearchPresets.scala, newswires/client/src/sharedTypes.ts, shared/types.ts
Fix the ingestion of the destinations field.
=> Ingestion: fix destinations field ingestion

newswires/client/src/App.tsx, newswires/client/src/DatePicker.tsx, newswires/client/src/Feed.tsx, newswires/client/src/SearchSummary.tsx
- Fix scrolling bar on the story list
- Fix search summary and date picker vertical spacing 
Before:
After:
=> UI: fix scrolling bar

README.md
Adds an architecture overview diagram.
Does it provide useful information, without being misleading?
=> Add architecture overview diagram

newswires/client/src/App.tsx, newswires/client/src/SearchSummary.tsx, newswires/client/src/SideNav.tsx, newswires/client/src/WireDetail.tsx, newswires/client/src/WireItemList.tsx
Fix various accessibility issues.
=> UI: fix accessibility issues

newswires/client/src/SideNav.tsx
=> Add all presets filter

newswires/client/src/ItemData.tsx
When retrieving story details, URL‑encode the search string so that reserved characters don’t disrupt the query parameters.
=> UI: encode text search when fetching story details

newswires/client/src/App.tsx, newswires/client/src/ResizableContainer.tsx, newswires/client/src/WireItemList.tsx, newswires/client/src/context/SearchContext.tsx
When returning to the list from a story don't jump to top.
=> UI: fix item list scrolling

newswires/client/src/App.tsx
Put hotkey event listeners on window; don't activate them when the target is a text input.
=> Fix global hotkey handling

newswires/client/src/App.tsx
Reverts guardian/newswires#287 -- I need to fix the logic which determines whether the focus is in an editable text field or similar
=> Revert "Fix global hotkey handling"

ingestion-lambda/src/handler.ts
Add HIGH_PRIOTIRY custom cat code to stories with a priority of 1.
=> Ingestion: handle high priority stories

ingestion-lambda/src/handler.ts
This particular file had formatting conflicts when trying to merge #290 into `main`, so I'm suggesting we format it in its own branch prior to merging #290. Planning to enforce prettier formatting on all js workspaces in this repo soon, but this will potentially disrupt some work in progress so just keeping it to this one file for the time being.
-   [ ] [The change doesn't use only colour to …
=> Format ingestion handler with prettier

newswires/client/src/App.tsx, newswires/client/src/Feed.tsx, newswires/client/src/SearchSummary.tsx, newswires/client/src/WireItemList.tsx, newswires/client/src/context/SearchContext.tsx, newswires/client/src/openTicker.ts, newswires/client/src/sharedTypes.ts, newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts, newswires/conf/routes
Add ticker routes:
- `ticker/feed`
- `ticker/item/1`
=> Add ticker routes

newswires/client/src/App.tsx, newswires/client/src/SearchSummary.tsx, newswires/client/src/Tooltip.tsx, newswires/client/src/WireItemList.tsx, newswires/client/src/fontStyles.ts
- Change default font to GuardianTextSans
- Replace px with rem
=> UI: update typography

README.md, cleanup-lambda/README.md, ingestion-lambda/README.md, poller-lambdas/README.md, scripts/setup, scripts/start
Add and clarify some documentation in the READMEs and scripts
Do the docs seem:
- Accurate?
- Worthwhile?
- Not overly-likely to get stale?
=> Misc. docs updates

newswires/client/package.json, package-lock.json
This dependency went missing at some point; add it back in.
=> Add missing storybook dependency

ingestion-lambda/src/db.ts, ingestion-lambda/src/handler.ts
This persists the s3Key to the database. 
=> Populate s3 key
