cdk/lib/__snapshots__/wires-feeds.test.ts.snap, cdk/lib/wires-feeds.ts
Sets UpdateReplacePolicy and DeletionPolicy on the topics and queues, to make sure they're not deleted by a cloudformation mistake
=> set updatereplace and deletionpolicies of Retain

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/newswires.ts
Lambda currently cannot access database, which makes sense because it doesn't have a security group granting it access.
Lambdas cannot be granted security group access unless they're in the VPC.
So add the lambda to the VPC.
Deploy to CODE, can the lambda now write to the DB (or at least fail at a different point than "connect ETIMEDOUT")?
=> lambda must be in VPC to get access to database

newswires/app/AppComponents.scala, newswires/app/conf/Database.scala, scripts/start
- Add a config function for connecting to the local postgres db
- Add a start script (modelled after [the Grid's `start.sh`](https://github.com/guardian/grid/blob/main/dev/script/start.sh) which:
- Checks for necessary dependencies
- By default will spin up the Docker containers, run the `ingestion-lambda` in 'dev' mode, and start the Play app.
- If passed the `--use-CODE` flag, it will establish a tunnel to the CODE db, if there isn't one already, and start the Play app. …
=> Add start script and local db config

docker-compose.yml
We depend on the `pg_trgm` extension which needs to be enabled for a given db. Adding the command in the docker-compose file will enable it.
- Run start script and then do a search in the UI. The request uses a `pg_trgm` operator so if it succeeds then the extension has been enabled.
- Dev-only, so no implications for CODE/PROD …
=> Configure `pg_trgm` extension in local db

newswires/client/src/App.tsx, newswires/client/src/Feed.tsx, newswires/client/src/SearchBox.tsx, newswires/client/src/WiresCards.tsx, newswires/client/src/debounce.ts, newswires/client/src/main.tsx, newswires/client/src/querify.ts, newswires/client/src/sharedTypes.ts, newswires/client/src/urlState.tsx, newswires/conf/routes
- [Extract WireData to sharedTypes file](https://github.com/guardian/newswires/pull/17/commits/b32800dfe159adda28e9f2085c9380eb11b31457)
- [Extract util functions](https://github.com/guardian/newswires/pull/17/commits/a5ac142b5e4a1b83269c446f3904cc0998f81686)
- [Rename PageStage/State to SearchState](https://github.com/guardian/newswires/pull/17/commits/cbcac43a8652ea1f7acbe348b2ffb38a8521fd16)
- [Add routing for home & feed pages](https://github.com/guardian/newswires/pull/17/commits/6190bc235818042c97fcfcc9d7a0df6ccb9b1717)
- Copies over the pattern from `state.tsx` [in the crosswordv2 app](https://github.com/guardian/crosswordv2/pull/293).
- [Add debouncing back in for incremental search](https://github.com/guardian/newswires/pull/17/commits/d506a8ca91c8515cccfdef6ae74e4c1e8db71eb4)
- …
=> Add routing and split out home from feed

newswires/client/src/Feed.tsx
Render an 'empty prompt' letting the user know that there are no results matching their query, if the API returns and empty array. (And don't render the wires card list unless there _are_ some results.)
=> Add 'no results' component to feed

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/newswires.ts
As on the title
Currently Cloudformation refuses to apply our stack definition, because version "16" currently defaults to "16.3", and our CODE instance is already running "16.4", and RDS cannot perform a downgrade.
We can revert this once "16" defaults to "16.4", and then go back to taking automatic minor version upgrades.
=> temporarily set the RDS minor version to 16.4, until RDS defaults version 16 to 16.4 or higher, when we can re-enable autoMinorVersionUpgrade

db/.gitignore, db/.scalafmt.conf, db/README.md, db/flyway.sc, db/flyway.toml, db/migrations/V1__Create_wires_table.sql, db/migrations/V2__trigram_indices.sql, ingestion-lambda/localRun.ts, scripts/start
start a directory of DB migrations, so the schema is version controlled and can be iterated on and applied to different environments safely.
I've struggled and generally been dissatisfied with play evolutions in previous projects, as it's generally designed to work with runtime dependency injection rather than our preferred usage of compile-time/explicit injection, so I'm going back to flyway; somewhat annoying that it's a new dependency, but it can be run and applied independently of the main app, and is much easier to configure, which I find a positive, and generally doesn't try to lead you down the minefield of building "down" migrations
=> start codifying db schema with migrations

db/flyway.sc, newswires/scripts/setup, scripts/start
This requirement is from an earlier iteration of #19 which used flyway directly, rather than through scala-cli. Update the dependencies and the setup script to account for the changes.
=> update start script required dependencies, and install scala-cli in setup script

ingestion-lambda/localRun.ts, ingestion-lambda/src/handler.ts, newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/WiresCards.tsx, newswires/client/src/sharedTypes.ts, newswires/conf/routes
- randomise values for `keywords` field in local ingestion-lambda
- add `/api/keywords` endpoint to expose all keywords in DB with a count of 'wire entry' where keyword is present - useful for filter options in UI plus a potential 'trending' feature
- add `inLastHours` and `limit` query params to the /api/keywords endpoint to better support a potential 'trending' feature (i.e. top 10 keywords in the last 24 hours)
- **split the `+` delimited string for `keywords` field into an array, during ingestion (ingestion-lambda)**
- update the API and client-side to expect keywords to be an array
The data in CODE needed to have existing entries updated to convert the `keywords` field of `content` column converted from string to array, which can be done by executing... 
```sql
UPDATE …
```
=> new `/api/keywords` endpoint

ingestion-lambda/src/handler.ts
empty strings are falsy, so messages with `keywords: ""` escaped being split into an array, but remained as strings so broke the deserializer in scala-land.
instead, always run split if a split function exists (ie. keywords is `string`), and default to an empty array (so the resulting entry can be parsed)
=> always split stringy keywords, even if empty string

db/migrations/V3__tsvector_indices.sql, newswires/app/db/FingerpostWireEntry.scala
Adds a brand new, generated tsvector column to all entries, which builds vector for the interesting text fields in the JSON data, then updates the query method to use that to search all the text fields together, and gets rid of the (pretty poor) trigram search
=> add the tsvector search column and indices

newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/App.tsx, newswires/client/src/Feed.tsx, newswires/client/src/SearchBox.tsx, newswires/client/src/sharedTypes.ts, newswires/client/src/useSearch.ts
- Since #27 the `query` function now takes limit and offset, making it virtually the same as `getAll` just with the addition of a WHERE clause. So, in anticipation of #30 (i.e. another where clause) it made sense to make the query/search string an Option and conditionally add the where clause, meaning we can remove the `getAll`. 
- In the process we clean up some redundant code left behind from #28.
- In anticipation of #30 returning some keyword counts/aggs alongside the (limited) search results, this PR wraps the results array in an object with a single key `results` and updates the client-side accordingly.
=> consolidate `getAll` into `query` function and wrap results array in an object with single key `results`

db/migrations/V4__keywords_index.sql, newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/sharedTypes.ts, newswires/conf/routes
- [add `keywords_index` via a DB migration](https://github.com/guardian/newswires/commit/4f29159f72259a8ddb55d7871ea9d0a32f4fd9f7)
- [add `keywords` query param option to the `/api/search` endpoint which takes a comma separated list of keywords that must all be matched](https://github.com/guardian/newswires/commit/9e7881f351e562ed6932b11485b3f2c9aaff81d3) 
- [return `keywordCounts` as an additional field in the `/api/search` response, to show the count of keywords (within the search results, but not limited like the actual data)](https://github.com/guardian/newswires/pull/30/commits/b0e26accee445ae8e5e82d5515ca80bc2064754a)
... this combined with #21 before it, should mean we can build an improved keyword aware search component 🎉
=> add proper `keywords` support to `/api/search` endpoint

newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/conf/routes
Prior to this PR our 'paging' was based on numerical offset, which can be problematic if the underlying data is changing (which it is as incoming items on the feed, may match the current search), more sensible is using the ID. Fortunately our ID is a `SERIAL` (so sequential). So this PR adds a `beforeId` query param to fetch X records with ids less than the on specified.
This can be used to facilitate infinite scroll by passing the ID of the last search result from the 'previous page' to fetch the next X older items, matching the current search.
=> add `beforeId` query param to `/api/search` and remove offset param to facilitate id-based pagination (e.g. for infinite scroll)

newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/conf/routes
To complement https://github.com/guardian/newswires/pull/33 (which introduced `beforeId` query param, mainly for infinite scroll purposes), here we add a `sinceId` query param to fetch only items since the most recent one that we're already aware of. This should be useful for polling (efficiently).
=> add `sinceId` query param to `/api/search` to ultimately facilitate polling

.sbtopts, newswires/build.sbt, newswires/conf/logback.xml
Copies the logback config that we're using in [crosswordv2](https://github.com/guardian/crosswordv2/commit/ad3cd755a1b04e94936fec2c18f1574b66cfb2d1)
It includes a number of changes to `build.sbt` as well. It might be that not all of these changes are necessary but I don't understand the jackson eviction stuff well enough to know what's needed and what's not.
Initially created because we thought that the broken log shipping was due to our config, though have since realised that there was an upstream issue with logging. Nevertheless, could be a QoL improvement to have nicer logs? …
=> Log-shipping fix: adopt crosswordv2 log settings

ingestion-lambda/src/handler.ts
Some stories are coming in with curly quotes escaped which isn't a valid JSON escape sequence as curly quotes don't need escaping. Detect, locate and remove these unnecessary escape sequences, eg `"\“abc\”"` -> `"“abc”"`
There's a few messages of this sort on the DLQ, we can redrive those once this is merged.
Fewer missing messages
=> strip badly escaped curly quotes when necessary

newswires/client/src/Feed.tsx, newswires/client/src/WireDetail.tsx, newswires/client/src/WireItemTable.tsx, newswires/client/src/WiresCards.tsx, newswires/client/src/formatTimestamp.ts
* Refactor the Feed component to use a table instead of a list of cards, to represent wire items.
* Build on this to add a timestamp to the table entries.
Trying to build effective formatting into the EuiCard component meant pushing against the grain of the framework, whereas a table layout facilitates it pretty well. Using the lower-level building blocks in Eui, rather than their opinionated EuiBasicTable component, meant we could get a pretty simple layout that works fine, imo.
**nb.** More of an opportunity than a regression: Eui's table component auto-scrolls to whichever row has focus, which is quite nice. We might want to rework keyboard support (including focus order etc.) later to see if we can get away with just leveraging Eui builtins? …
=> Add timestamps to feed

newswires/client/src/WireDetail.tsx
Now we're getting more wires in, there are a lot of entries that don't have fields like bylines. We've also got quite a lot of records with `keywords: [""]`, which was getting rendered as a single empty keyword badge.
* Refactor to use JSX components directly as children, to make conditional rendering logic more familiar.
* Do some checks on the presence of fields before trying to render them.
- …
=> Refactor detail list and don't render fields without meaningful data

ingestion-lambda/src/handler.test.ts, ingestion-lambda/src/handler.ts
* Deduplicate keywords on ingestion.
* Strip leading and trailing whitespace.
* Don't save empty strings.
* Unit tests for the above.
=> Dedupe keywords and handle edge cases

newswires/client/src/main.tsx
This integrates https://github.com/guardian/pinboard in its current form. This is just the initial integration phase, and hopefully some additional/deeper integrations will follow (mostly on the pinboard side most likely).
=> load pinboard 📌

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/newswires.ts
When dumping lots of messages onto the queues at once (eg. redriving the DLQ) we dont want the lambda to spin up hundreds of simultaneous executions... this will overwhelm the database which is bad!
Sets the max concurrency to 10, and since each execution can handle up to 10 messages, this is up-to 100 messages inflight simultaneously which should be more than enough even for redrives!
=> Set max concurrency for ingestor

newswires/client/src/WireDetail.tsx
`EuiCodeBlock` can do syntax highlighting for us, and applies `pre-wrap` to the JSON text, which imo makes it a little easier to read?
=> Use EuiCodeBlock for JSON display

newswires/client/src/WireItemTable.tsx
Request from @KarenFrankel9 to put 'slug' field first in the wire cards, with `headline` as a fallback. Headline is displayed as the secondary line, unless it's used for the first line.
This resolves an issue where there were frequent cards with no heading at all. We also discussed whether it would make sense to put the headline first for some agencies, and the slug first for others. Should be easy to experiment with as we go.
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-te …
=> Prefer slug for cards, fall back to headline

newswires/app/AppComponents.scala, newswires/client/package-lock.json, newswires/client/package.json, newswires/client/src/App.tsx, newswires/client/src/Feed.tsx, newswires/client/src/Item.tsx, newswires/client/src/SideNav.tsx, newswires/client/src/icons.ts, newswires/client/src/urlState.ts, newswires/client/src/useSearch.tsx
Add a side navigation panel, and rework the feed/item split to use resizeable containers (on desktop)
(more images below)
- [Filter & dedupe queries before adding to history](https://github.com/guardian/newswires/pull/51/commits/ba3abd29ea5d7cdfc2d050b45449bf30ccc71945)
- [Use JsonHttpErrorHandler](https://github.com/guardian/newswires/pull/51/commits/bae1c9bc2f631538a94be0efc3512b9d5c915d76)
- [Handle API errors better](https://github.com/guardian/newswires/pull/51/commits/50783c14ec98cd8358001eed4c4d1075251933fc)
- [Add side nav, hide feed for mobile item view](https://github.com/guardian/newswires/pull/51/commits/601b5d02e13becc00ae049e4066a8f0a8f3e2f3d)
<details>
<summary>
Item view (mobile and desktop)
</summary> 
</details>
<details>
<summary>
Feed view (mobile, desktop, with …
=> Add side navigation and resizeable panels

.github/workflows/ci.yaml, newswires/client/src/SideNav.tsx, newswires/client/src/sharedTypes.ts, newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts
Updates the Query type, and the URLs that the currently hardcoded side navs link to, to match the new supplier searches added in #60
=> Side nav supplier searches

newswires/client/package-lock.json
Run `npm audit fix` to clear the automatically resolvable dependency warnings
=> Remove vulnerability warnings with `npm audit fix`

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/newswires.ts
gp2 has low baseline performance and relies on bursting to keep up with demand. gp3 has a baseline performance equal to gp2's max burst and is cheaper.
If this isn't sufficient, or if increased future usage means we need to scale up, we can look at provisioning the IOPS while on gp3, or moving again to io1 or io2 for further configuration.
=> Switch db instance storage type to gp3

db/migrations/V6__drop_trigram_indices.sql
Originally added in #19 to quickly allow some sort of text searching without setting up `tsvector` indexes... those are set up and working pretty nicely now, so these indexes should now be unused and so deletable.
=> drop now-unnecessary trigram indexes

newswires/app/db/FingerpostWireEntry.scala
Also clearly parse querytext as English
`phraseto_tsquery` parses the query text with the same idea as googling, or github searching with double quotes around the text - ie. looks for runs of the same words, not just a document which contains each word somewhere, even if there's little or no relation between them. 
`websearch_to_tsquery` parses queries in a similar manner as users familiar with Google would expect - double quotes for phrase searches (as above), `-` for negative searches, and even respects `or` as a keyword for optional searches.
=> use websearch_to_tsquery for textsearch

newswires/app/controllers/QueryController.scala, newswires/client/.eslintrc.cjs, newswires/client/src/Item.tsx, newswires/client/src/panda-session.ts, newswires/client/src/useSearch.tsx
Brings in panda-session so we can get automated session refreshes and keep wires users wiring for longer
=> include panda-session for automatic session refreshes

.github/workflows/snyk.yaml
Snyk docs say it should autodetect projects within the first few directories, so maybe we don't even need to specify the projects it should be looking at
Attempt to fix up #58
=> try snyk without setting working directory

newswires/client/src/App.tsx, newswires/client/src/SearchBox.tsx, newswires/client/src/SideNav.tsx, newswires/client/src/sharedStyles.tsx, newswires/client/src/sharedTypes.ts, newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts, newswires/client/src/useSearch.tsx
- Add supplier filters and search history to the sidebar.
- Add support on the front end for `subject` searches.
- Updating the text search via the UI happens _within_ the selected set of suppliers, now, rather than overwriting the whole query.
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use- …
=> Richer search UI in sidebar

newswires/client/src/App.tsx, newswires/client/src/WireItemTable.tsx, newswires/client/src/icons.ts
Popout tickers are a useful part of the current wires solution, so this PR adds a basic implementation.
Here we piggy back on the fact newswires works nicely at mobile breakpoints already, and:
- add a new `Popout as ticker` (sticky) button at the top of search results with uses `window.open` (with the `popout=true`) option to (re)open itself in a small popup window (easy thanks to persistent URLs)
- given opening a popup populates the `window.opener` property we can detect whether we're open in a popup and hide the heading bar and the `Popout as ticker` button for more streamlined view.
This solution requires very little extra maintenance (when compared with dedicated components for pop-out ticker).
In future, it would be good to also offer tickers within the main window, perhaps docked …
=> add `Popout as ticker` button to search results

newswires/client/src/WireDetail.tsx
Add data attribute to allow Pinboard to identify the body text of an item for snippet selection.
=> Add pinboard selection target

newswires/client/src/App.tsx, newswires/client/src/SearchBox.tsx, newswires/client/src/SideNav.tsx
- Move search bar to side nav
- Refactor `SearchBox` component so that it consumes global values from `useSearch` directly, rather than having them passed as children.
=> Put search in side nav

db/migrations/V7__keywords_nonpath_index.sql, db/migrations/V8__subject_codes_index.sql, newswires/app/conf/SourceFeedSupplierMapping.scala, newswires/app/controllers/QueryController.scala, newswires/app/db/CustomMappers.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/app/db/SearchParams.scala, newswires/client/src/SideNav.tsx, newswires/client/src/sharedTypes.ts, newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts
As much as you should be able to request to see wires matching suppliers or keywords (and soon subjects), you should _also_ be able to exclude certain suppliers or keywords. 
This is trickier in the DB queries, because postgres seems reluctant or unable to use the indexes that support the positive queries for negative. Thanks to a very handy stack overflow post, there is a trick that allows you to work around this, by querying for the rows which do match the exclusion parameters, then exclude _those_ rows from the real query. Because you're only searching the DB in a positive manner, postgres seems much happier/able to use the indexes for fast querying. …
=> Parameters to exclude wires categories

newswires/client/src/App.tsx, newswires/client/src/SideNav.tsx, newswires/client/src/WireItemTable.tsx, newswires/client/src/sharedTypes.ts, newswires/client/src/useSearch.tsx
- Add an 'auto update' toggle switch in the side nav
- Move the 'new ticker' button to the top bar
- And add a pass-by refactor to have it always open the new tab in 'feed' view
=> Add auto-update toggle switch

newswires/client/src/SideNav.tsx
Undock on medium; also fixes the issue where clicking overlay outside of the menu would _both_ close the menu _and_ propagate the click to the layer below.
=> Undock side nav on smaller screens

newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/Item.tsx, newswires/client/src/WireDetail.tsx, newswires/client/src/WireItemTable.tsx, newswires/client/src/sharedTypes.ts, newswires/conf/routes
- Add a `highlight` column, that should return a `ts_headline` for the given query, if there's a free text search as part of that query
- Display the highlight column in the main feed table, and use the highlighted `bodyText` as the markup for the main item display, if we have it.
- nb. the highlighting is achieved by adding `<mark>` elements either side of the search terms, which means that the markup in the body text on the page won't be quite the same as the markup that we have stored in the db for the story. We should bear this in mind when working on the 'import to composer' via pinboard functionality (cc. @twrichards) though I don't think it's a huge issue. 
- Tweak the main feed table to use a 'responsive' layout whenever an item is selected, as there's reduced horizontal space but …
=> Highlight search terms in results

cdk/bin/cdk.ts, cdk/lib/__snapshots__/riffraff.test.ts.snap, cdk/lib/riffraff.test.ts
The Newswires stack references the queue exposed by the WiresFeeds stack, cdk automagically does this via cfn outputs under the hood. The generated riff-raff.yaml has no idea about this relationship but the two stacks have separate cfn deployments, which by default execute in parallel, creating a race condition.
This PR...
- first snapshot tests the generated riff-raff yaml (as that's useful in its own right)
- second, it makes use of `addDependency` (added in https://github.com/guardian/cdk/pull/2094) to add that dependency (which shows up in the test snapshot)
=> add riff-raff dependency for Newswires cfn deploy on the WiresFeeds cfn deploy (plus snapshot test the riff-raff.yaml)

poller-lambdas/package.json, poller-lambdas/src/index.ts, poller-lambdas/src/pollers/EXAMPLE_fixed_frequency.ts, poller-lambdas/src/pollers/EXAMPLE_long_polling.ts, poller-lambdas/tsconfig.json
Add `.tsconfig` and lint script to the `poller-lambdas` workspace and fix linting errors surfaced by this. (All changes should be no-ops.)
=> Linting for polling lambdas

ingestion-lambda/localRun.ts, ingestion-lambda/src/handler.ts, package-lock.json, package.json, shared/types.ts
Add Zod schemas and types that describe the expected shape of payloads to the ingestion lambda. Use the schemas to validate the payload of the SQS messages which feed the lambda.
This is a preparatory step for adding our own data sources which will feed the ingestion lambda, which will help us to make sure we're writing what we expect to read.
-   [ ] [The change doesn't use only colour to …
=> Add ingestor data validation

newswires/app/conf/SourceFeedSupplierMapping.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/WireItemTable.tsx, newswires/client/src/sharedTypes.ts
Display the supplier in the feed to identify the source of each item.
**Given** the feed items have been populated in the database
**When** going to the main feed page
**Then** the supplier should be displayed for each feed item
Displaying the feed supplier for each feed item allows users to identify the source of each item and compare items coming from Fingerpost with items ingested directly from the supplier.
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visu …
=> Display fingerpost supplier on the feed

.gitignore, cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/__snapshots__/riffraff.test.ts.snap, cdk/lib/constructs/pollerLambda.ts, package.json, poller-lambdas/localRun.ts, poller-lambdas/src/index.ts, poller-lambdas/src/pollers/ap/apPoller.ts, poller-lambdas/src/pollers/reuters/reutersPoller.ts, shared/pollers.ts
- Add minimal definition of Reuters and AP poller lambdas, using the patterns added in #83:
- d878e2fee6628a1d19cfddd77db51d9a47fe5a23
- 9c2816cf2899e729b64518ce26a7858f80af7696 
- Fixes the poller lambdas `index.ts` export, so that the lambdas can find the right function to run: 548ac91cf23b539513170e0183e263ff84b2fbb4
Getting this merged into `main` will make the branch deployable to CODE again, and the actual business logic for the two pollers can then be added at a later point. …
=> Initial AP and Reuters poller infra

jest.config.js, poller-lambdas/package.json, poller-lambdas/src/test.test.ts
Add config and a demo Jest test for the `poller-lambdas` project, in preparation for adding some actual tests.
=> Jest setup for `poller-lambdas` project

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/constructs/pollerLambda.ts, poller-lambdas/src/index.ts, poller-lambdas/src/types.ts
Add a mechanism allowing a poller lambda to update its own secret.
This will be used in the upcoming #92 PR, to store an auth token in the secret that can be re-used across multiple lambda runs while it's still valid.
=> Pollers can update their own secrets

.gitignore, newswires/client/package-lock.json, newswires/client/package.json, newswires/client/src/App.tsx, newswires/client/src/Feed.tsx, newswires/client/src/Item.tsx, newswires/client/src/SearchBox.tsx, newswires/client/src/SideNav.tsx, newswires/client/src/WireItemTable.tsx, newswires/client/src/context/SearchContext.test.tsx, newswires/client/src/context/SearchContext.tsx, newswires/client/src/context/SearchReducer.test.ts, newswires/client/src/context/SearchReducer.ts, newswires/client/src/context/fetchResults.test.ts, newswires/client/src/context/fetchResults.ts, newswires/client/src/main.tsx, newswires/client/src/tests/fixtures/wireData.ts, newswires/client/src/tests/testHelpers.ts, newswires/client/src/urlState.ts
Add offline banner when data update fails on Newswire UI.
=> Newswires-UI: add offline banner when data update fails

newswires/app/conf/SourceFeedSupplierMapping.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/SideNav.tsx, newswires/client/src/WireDetail.tsx, newswires/client/src/sharedTypes.ts
Add a new suppliers: `GuAP` and `GuReuters`, which collects items with `source-feed: AP-Newswires` and `source-feed: Reuters-Newswires`. These are items passed to the ingestion system by the AP poller lambda added in #93, #98 and #92. These suppliers are now included in both the front end and the back end.
Also passes the `ednote` field through to the UI.
-   [ ] [The change doesn't use only …
=> Add our own AP & Reuters feeds to API/UI

newswires/client/src/context/SearchReducer.test.ts, newswires/client/src/context/SearchReducer.ts
Enable toggle auto-update regardless of the search status.
=> Newswires UI: fix toggle auto-update

newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/WireDetail.tsx
Passes a couple of extra fields from `content` down to the UI, and includes the wrapper around the content in the JSON view.
More info for debugging.
=> Add more fields to JSON view in UI

newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/WireDetail.tsx, poller-lambdas/src/pollers/reuters/auth.ts, poller-lambdas/src/pollers/reuters/reutersPoller.ts, scripts/get-reuters-item.sh, shared/pollers.ts
First pass at business logic for Reuters feed.
* Read auth token from Secrets
* If the auth token fails, try to request a new one to use for subsequent calls using the client id and secret from Secrets
* nb. as per our conversation with Reuters' API team there is not currently a supported method for getting 'only new items since last poll', so this is my suggested heuristic for getting new stories, though it's not foolproof
* this means there will be overlap between any two consecutive queries, but currently opting to rely on the ingestion lambda to deduplicate stories unless this proves problematic for performance or other reasons
The poller lambda wrapper, as of #99, will check this value and update the Secret value if needed.
---
The implementation of (1) adds a little complexity and …
=> Reuters poller business logic

poller-lambdas/src/pollers/ap/apPoller.test.ts, poller-lambdas/src/pollers/ap/apPoller.ts, poller-lambdas/src/pollers/ap/fixtures/apItems.ts, shared/types.ts
Link AP images to wire stories.
=> AP poller: link AP images to wire stories

newswires/client/src/App.tsx
Make the offline banner fixed so it can remain visible when scrolling through stories.
=> Newswires UI: fix offline banner

newswires/client/src/context/SearchContext.tsx
If there are no existing results, then the `Math.max()` call returns `-Infinity`, which is not a valid id for the API.
To replicate the issue: Search for a phrase that won't exist in the database, then observe that while the initial search returns a 200 and an empty list of results, subsequent auto-update `fetch` requests receive a 400.
To test the fix: Make the same search and observer that auto-update requests receive a 200 with empty results.
=> Fix update action after empty result

newswires/client/src/Feed.tsx, newswires/client/src/WireItemTable.tsx, newswires/client/src/context/SearchContext.tsx, newswires/client/src/context/SearchReducer.test.ts, newswires/client/src/context/SearchReducer.ts, newswires/client/src/context/fetchResults.test.ts, newswires/client/src/context/fetchResults.ts, newswires/client/src/urlState.ts
Add a load more button to view older stories.
=> Newswires UI: add pagination

newswires/app/conf/SourceFeedSupplierMapping.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/suppliers.ts
* [Add Comet to suppliers on front and back ends](https://github.com/guardian/newswires/commit/c4026281ccdf29cb3eac0fa38d76325fa3120662)
* [Use sourceFeed as fallback value in API when supplier isn't recognised](https://github.com/guardian/newswires/commit/fc346dacc6eb0195b52189f44fa4d92f477bdfb5) …
=> Add comet to suppliers

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/newswires.ts, ingestion-lambda/src/handler.ts, shared/constants.ts
- Add a logs metric filter to the log group for the ingestion lambda, which collects the `sourceFeed` from successfully ingested items.
- Also adds the corresponding logging to the lambda handler code.
=> Add log metric filter for source feeds on ingestion

newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/Feed.tsx, newswires/client/src/SearchBox.tsx, newswires/client/src/SearchSummary.tsx, newswires/client/src/WireItemList.tsx, newswires/client/src/context/SearchContext.test.tsx, newswires/client/src/context/SearchReducer.test.ts, newswires/client/src/context/SearchReducer.ts, newswires/client/src/context/fetchResults.test.ts, newswires/client/src/sharedTypes.ts
=> Newswires UI: add search summary

.github/workflows/ci.yaml, cdk/package.json, poller-lambdas/localRun.ts, poller-lambdas/src/pollers/EXAMPLE_fixed_frequency.ts, poller-lambdas/src/pollers/EXAMPLE_long_polling.ts, poller-lambdas/src/pollers/ap/apPoller.test.ts
- Add `typecheck` script to `cdk` workspace, and run `npm run typecheck` for all workspaces in CI.
- Fix some type errors introduced by #124
=> Typecheck in CI, and fix type errors

poller-lambdas/src/index.ts
Change `Math.min()` to `Math.max()` when calculating `safeIdealFrequencyInSeconds`, which is used to decide when to schedule the next invocation of a scheduled poller lambda.
The previous code had the effect of making 5 seconds the _ceiling_ for the ideal interval, rather than the _floor_ (which is what was intended). The `idealFrequencyInSeconds` set for a given poller was therefore being ignored unless it was < 5 seconds. 
This will mean that the Reuters poller in particular is running less often than it has been, which means a) stories will come in slower sometimes, and b) it's more likely that we'll drop stories in the case where they fail first time, because trying more regularly was effectively giving us many retries per story. But this is a separate issue strictly speaking and I've …
=> Fix self-invocation for fixed schedule poller lambdas

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/newswires.ts, ingestion-lambda/src/handler.ts, poller-lambdas/src/pollers/ap/apPoller.ts, shared/constants.ts
- Log the externalId of successfully ingested items, along with some other metadata.
- Make the namespacing more consistent for eventTypes.
- Use `logger` helper for logging in `apPoller`.
Logging `externalId` and `sqsMessageId` in more places makes it easier to track a given story across lambda, and easier to track the steps within a given lambda, respectively.
-   [ ] [The change doesn't use …
=> More logging on ingestion-lambda and AP poller

db/migrations/V12__composer_link_cols.sql
adds in migration to add columns for storing composer ID and identity of user sending to composer, so that the wire and the piece are linked and can be visited.
Migrate locally.
Unblocks faster development of #139 when running locally against the CODE database.
=> Add db migration to hold composer IDs against wire entry

newswires/app/controllers/ViteController.scala, newswires/app/views/fragments/clientConfig.scala.html, newswires/client/index.html
- Inject config into client SPA entrypoint (`index.html`) at runtime.
- Refactor ViteController to contain CSRF injection and config injection in a single function, to make it easier to keep dev server and prod server config in sync.
Runtime consumption of config on the `Window` by the client was introduced in #141. This PR builds on that, to inject the config at runtime. The config is still hard coded, but by generating the JS code from Scala code, we take another step towards the eventual goal of generating dynamic client config on the server at runtime.
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-te …
=> Pass client config from ViteController

newswires/client/src/WireDetail.tsx
Set `wrapText={true}` for subject labels in WireDetail component. This prevents long lines from breaking layout. 
The `<ListGroupItem>` component from eUI truncates long labels by default, but this behaviour doesn't always seem to work when switching from one wire item to another. I don't think there's any problem with wrapping the text here, so it seems like a good fix.
=> Fix: Wire detail panel sometimes extends past edge of window

db/migrations/V13__category_codes_column.sql, ingestion-lambda/localRun.ts, ingestion-lambda/src/categoryCodes.test.ts, ingestion-lambda/src/categoryCodes.ts, ingestion-lambda/src/handler.ts, newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/sharedTypes.ts, newswires/client/src/tests/fixtures/wireData.ts
- Add `category_codes` column to the database (migration script has been run against CODE already).
- Populate the new column from the ingestion lambda. Currently defaults to an empty array for all suppliers except AP. Other suppliers will be added later.
- Let the API and UI know about the new column, though currently we're just reading it (will add queries on it in future PR)
Deploy to CODE, check:
```
// incoming data (preserved as-is, in 'content'):
"subjects": {
"code": [
"iptccat:i+a",
"service:"
]
},
// new field, generated from incoming data by ingestion lambda
"categoryCodes": [
"iptccat:i",
"iptccat:a"
],
```
New, non-AP: https://newswires.local.dev-gutools.co.uk/item/1258297
```
"id": 1258297,
"supplier": "PA",
"externalId": "PA PA SPORT …
```
=> Add 'category_codes' column, populate it for incoming AP stories

ingestion-lambda/src/categoryCodes.test.ts, ingestion-lambda/src/categoryCodes.ts
When we receive them from Fingerpost they're labelled with the prefix `iptccat:`, but the codes seem to actually be [AP category codes](https://developer.ap.org/ap-media-api/agent/AP_Classification_Metadata.htm) instead. This change relabels them at ingestion, while we're putting them into the `category_codes` column.
As before, other prefixes will be either filtered out (`service:`) or passed through unchanged (everything else).
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and …
=> Rename cat codes labelled 'iptccat' as 'apCat' instead

newswires/client/src/Item.tsx, newswires/client/src/WireItemList.tsx
Feed list: 
* main heading: use `headline` in preference to `slug` for the main heading; only use slug if there is no headline.
* sub heading: instead of using the `headline`, use the `subhead` if it's present, or the first 100 characters of the body text if not. Only show if it's not the same as the heading.
Detail view:
Show the `slug` as part of the headline, but visually de-emphasized unless there is no `headline`.
This seems like the 'right' way to use `slug`, `headline` and `subhead`, and it's more in line with how the agencies render their own content. There are cases where this doesn't work perfectly for our current data (noted below) but it feels like we should try to fix those upstream unless that's not possible.
These are not ideal, but it feels most sensible to try and fix …
=> Fix: More sensible handling of headline and subhead in wires list

newswires/client/src/WireItemList.tsx
* Fix a bug in the wire feed card layout, whereby the time stamp was being pushed down to the bottom of the card if the date was also showing (i.e. when it wasn't today's date)
* Move the supplier badge to the right hand side, under the date, to de-emphasise
* Fix a regression whereby the main heading wasn't being rendered in bolder text anymore
* When we have a search highlight to show, don't render other secondary content.
|Before|After|
|-|-|
|<img width="971" alt="image" src="https://github.com/user-attachments/assets/071aae86-9051-48d3-9209-bc3f473b0527" />|<img width="966" alt="image" src="https://github.com/user-attachments/assets/980de542-4464-4cd9-9ce2-7523d3311cee" />|
|<img width="975" alt="image" src="https://github.com/user-attachments/assets/659fae64-aed3-4114-911a-d771a08917 …
=> Feed card layout tweaks

newswires/app/controllers/QueryController.scala, newswires/app/controllers/ViteController.scala, newswires/app/service/FeatureSwitchProvider.scala, newswires/client/src/context/SearchContext.test.tsx, newswires/client/src/context/SearchContext.tsx, newswires/client/src/serverSideConfig.ts/serverSideConfig.ts, newswires/client/src/serverSideConfig.ts/windowConfigType.ts, newswires/client/src/suppliers.ts
Adds a `FeatureSwitchProvider` object which contains config for feature switches, and exposes a limited set of public methods that will hopefully make feature switch use intuitive and clear, i.e. it currently just exposes lists of switches, which have an `isOn` method.
Possibly over-engineering given that we've only got a single case at the moment. I lean towards thinking it's worthwhile because it will hopefully help us stay disciplined when adding this kind of logic, but open to other perspectives.
Also refactors the client side filtering out of `Gu*` suppliers so that it consumes the same switch, rather than consuming a list of suppliers to filter out. There's a bit more code duplication here but it seems overall simpler to have the contract between the client and server fit the same …
=> Add FeatureSwitchProvider and use it for 'show Gu suppliers' functionality

newswires/app/conf/SearchBuckets.scala, newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/app/db/SearchParams.scala, newswires/client/src/context/SearchContext.tsx, newswires/client/src/sharedTypes.ts, newswires/client/src/urlState.ts, newswires/conf/routes
* Add a set of criteria for the AP World bucket that is loosely based on the Fingerpost criteria. General sense-checking seems to suggest that it's catching the right content, and I'd suggest that we should iterate on it as we go if refinements are required (and this should be easier once the initial pass is merged, so everyone can see it).
* To support the new bucket, this branch also adds the ability to query on the `category_codes` column that was added in #150  …
=> Initial fingerpost-based AP world bucket

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/newswires.ts
We were meaning to do this anyway (see the TODO that are now gone) but it also address an FSBP finding. 
NOTE: Unfortunately we still need to leave the version explicitly set to 16.4 (since CFNs default is 16.3 and it can't downgrade), which kind of makes the autoMinorUpgrades problematic since they will force the CDK out of sync with reality 🙄 .
=> re-enable 'automatic minor version upgrades' for the postgres DB

ingestion-lambda/src/categoryCodes.test.ts, ingestion-lambda/src/categoryCodes.ts, ingestion-lambda/src/handler.ts
- Handle incoming AFP subject codes in the same way as AP codes (introduced in #150)
- Fix a small bug in the AP code parsing which would pass through 'empty' tags with no actual code attached (i.e. `iptccat:`) 
=> Process AFP category codes on ingestion

newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/app/db/SearchParams.scala, newswires/client/src/App.tsx, newswires/client/src/DatePicker.tsx, newswires/client/src/Feed.tsx, newswires/client/src/SearchSummary.tsx, newswires/client/src/SideNav.tsx, newswires/client/src/context/SearchContext.tsx, newswires/client/src/context/SearchReducer.test.ts, newswires/client/src/context/SearchReducer.ts, newswires/client/src/context/fetchResults.test.ts, newswires/client/src/context/fetchResults.ts, newswires/client/src/dateConstants.ts, newswires/client/src/dateMathHelpers.test.ts, newswires/client/src/dateMathHelpers.ts, newswires/client/src/icons.ts, newswires/client/src/sharedTypes.ts, newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts, newswires/client/tsconfig.json, newswires/conf/routes
Filter stories by date:
1. Provides a way to filter stories by date using relative or/and absolute dates.
2. By default, it only shows stories ingested during the past two weeks.
3. The URL get updated with only required information (e.g. when the end date is set to `now`, it is not necessary to include in the URL).
1. Click on dropdown to get access to the `Quick select` and `Commonly used` menus.
2. Click on date button (showing `Today` in the screenshot) to get access to the advanced date time menu.
Summarises the selected date range and allows to reset it.
Today:
Last 24 hours:
The date range is reflected in the URL.
When the end date is set to `now`, it can be omitted from the URL.
Updates the history and can be combined with other filters. …
=> Newswires UI: filter search by date

newswires/app/db/FingerpostWireEntry.scala, newswires/build.sbt, newswires/test/db/FingerpostWireEntrySpec.scala
Our SQL query building is getting sufficiently complex that it feels sensible to have some unit tests documenting the way we expect a given set of `SearchParams` to be rendered in SQL.
There's a risk of over-testing implementation details, so I've just added a couple of basic tests for now. One of them has already caught a small bug (the category codes inclusion clause being added twice) which I've fixed here too.
Having some level of test coverage here will hopefully help us document changes and catch accidental regressions.
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboar …
=> Add basic SQL generation tests

newswires/app/controllers/QueryController.scala
We want to exclude feeds from our own pollers if the `showGuSuppliers` switch is _off_, not _on_ 🤦
=> Fix behaviour based on feature switch

newswires/client/src/Disclosure.stories.tsx, newswires/client/src/Disclosure.tsx, newswires/client/src/Item.stories.tsx, newswires/client/src/WireDetail.tsx, newswires/client/src/icons.ts
- Add a simple 'Disclosure' component (12a310b67c2b628239e360cb9ae4a73b356cad6a)
- Add a 'Metadata' section to the wire Item view:
- Move 'subjects' to a table in this section (collapsed by default -- some items have 80+ subjects!) (bb1ccd6511709046c3cddb292428de92daefbcd1)
- Also add a 'general metadata' table, open by default (7f8373db59a16ee27056c53f3f8b1a1be0e80479)
**nb.** Currently showing 'content.subjects', but I'm planning to switch this over to the top-level 'categoryCodes' list once all the suppliers are having this set properly.
- `npm run storybook`
- or `./scripts/start --use-CODE`
Hopefully interested parties will be able to find what they want, whereas uninterested parties won't be distracted by long lists of subjects etc. …
=> Add metadata table for wire item

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/newswires.ts, ingestion-lambda/src/handler.ts
The metric filter wasn't working, perhaps because we changed the logging format to work with ELK. Either way, currently the data we're logging for ELK is also parseable by Cloudwatch, but the field it was looking for in the metric filter wasn't on _that_ logging.
Solution: Adapt the metric filter to match the existing ELK logging (switching it over to care about supplier now, instead of source feed, as that's the more useful thing to graph) and delete the other logging as it was only there for the metric before.
-   [ ] …
=> Fix mismatch between metric filter and logging

newswires/app/conf/SearchBuckets.scala, newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/test/db/FingerpostWireEntrySpec.scala, newswires/test/helpers/WhereClauseMatcher.scala
Only include the Economic news subject code (MCC:OEC) when the headline includes "News Summary".
Reference: https://github.com/guardian/newswires/pull/154
Buckets can now have a multiple search params in order to only filter `MCC:OEC` stories by headline.
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-vis …
=> Newswires backend: improve Reuters World filtering

ingestion-lambda/src/handler.test.ts, ingestion-lambda/src/handler.ts
Fix bug that omits body text from stories when saving them to the DB.
=> Newswires ingestor: fix stories body text

newswires/app/conf/SearchBuckets.scala, newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/app/db/SearchParams.scala, newswires/client/src/SearchSummary.tsx, newswires/client/src/SideNav.tsx, newswires/client/src/WireDetail.tsx, newswires/client/src/sharedTypes.ts, newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts, newswires/conf/routes, newswires/test/db/FingerpostWireEntrySpec.scala
Use Category Codes instead of Subjects in the UI, and in search.
As of #200 the intention is for all useful subject data to be captured in the 'categoryCodes' field, which is more standardised and easier/quicker to search given that it's not wrapped in a JSON column.
Unless there are serious issues we should aim to fix forward any issues with categoryCode search that come up.
I'm leaving subject info in the API response at it could be helpful for debugging, but in theory we shouldn't have any need for this field after ingestion.
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyb …
=> Deprecate subjects in favour of category codes

newswires/app/conf/SearchBuckets.scala, newswires/client/src/SideNav.tsx
Adds a new bucket for 'AFP World'. It represents the existing Fip logic, as I understand it: everything goes into 'world' from AFP, except items with the `SPO` category.
- `./scripts/start --use-CODE`, check that the bucket loads and contains nothing with the sport category code
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/peop …
=> Add AFP World bucket

ingestion-lambda/src/suppliers.ts, newswires/client/src/suppliers.ts
```
newswires=> select distinct(content->>'source-feed') from fingerpost_wire_entry where supplier='Unknown';
?column?      
--------------------
WIREFAST
PA ZEN INTERNET
PA PRESSWIRE
PA EDREAMS ODIGEO
PA TRUSSEL
PA ACCESS NEWSWIRE
(6 rows)
```
Looks like Wirefast is sticking around for the time being. The rest look like they're clearly from PA.
-   [ ] [The change doesn't use only colour to …
=> Put comet and wirefast into 'minor agencies' supplier, update PA sourcefeed list

newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/test/db/FingerpostWireEntrySpec.scala
Join user defined search with bucket search with AND while querying stories.
=> Newswires backend: join search params with AND

newswires/app/conf/SearchBuckets.scala
Exclude Reuters Business stories from Reuters World.
Only include Reuters Business stories that contain `News Summary`.
=> Backend: exclude Reuters Business from World

newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/WireDetail.tsx, newswires/client/src/WireItemList.tsx, newswires/client/src/sharedTypes.ts
We return highlights in two slightly different ways - the item endpoint will return them enclosed in `<mark>`, and the search endpoint will return them in the default `<b>`. 
Separately, the backend considers the highlight to be optional, and may not be returned (under a few circumstances, but importantly if the text query appears in one of the [fields other than the body copy in the combined textsearch index](https://github.com/guardian/newswires/blob/main/db/migrations/V3__tsvector_indices.sql#L4-L9), but a few parts of the frontend considered it to be mandatory, causing validation errors when parsing. Normalise it into being optional everywhere.
Make some searches that would return items without a highlight - searching for common keyword terms should do it. Try "government" for example …
=> More consistent highlight

ingestion-lambda/src/handler.test.ts, ingestion-lambda/src/handler.ts
Replaces consecutive newlines (and spaces) with one `<br />` to reduce spacing between paragraphs in body text.
=> UI: reduce space between body text paragraphs

ingestion-lambda/src/handler.test.ts, ingestion-lambda/src/handler.ts
We receive a bunch of input documents where the body text field contains a literal tab or newline character (rather than the usual "\t" or "\n" escaped versions), which are invalid in JSON. Make a best effort to fix them up, but this is a little tricky as these whitespace characters are valid outside of JSON strings (ie. as indentation around the object literal).
Fortunately they can be safely replaced with " "s, in both locations!
Tested on CODE, where the remaining 234 messages on the DLQ were redriven through the lambda running this updated code with success.
More messages make it onto newswires without parsing failures
=> ingestion: fix bad control characters

newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/WireDetail.tsx, newswires/client/src/WireItemList.tsx, newswires/client/src/context/SearchReducer.test.ts, newswires/client/src/dateHelpers.ts, newswires/client/src/tests/fixtures/wireData.ts
Make timestamps consistent in UI:
- Convert timestamps to `Instant` objects on the backend to ensure compatibility with MomentJS.  
- Display `ingestedAt` instead of `versionCreated` in the story list for consistency with sorting and filtering, which use `ingestedAt`.  
- Display timestamps in local time on the story details component. …
=> Newswires UI: make timestamps consistent

newswires/app/conf/SearchBuckets.scala, newswires/client/src/DatePicker.tsx, newswires/client/src/dateConstants.ts, newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts, package.json
- Reduce default time window to one day (Today) to improve `All World` saved search performance.
- Combine buckets into one to support `All World` saved search.
=> UI: set default time range to Today

newswires/client/src/WireDetail.tsx
Include a supplier badge in the story details, as the supplier information isn't displayed clearly on small screens.
=> UI: add supplier badge to story details

newswires/client/src/WireItemList.tsx
Add more context to stories by appending the slug to story headline in wires list for AAP stories.
=> UI: append slug to headline in wire list for AAP

newswires/client/src/WireDetail.tsx, newswires/client/src/context/SearchReducer.ts, newswires/client/src/dateHelpers.ts
Include the elapsed time at the top of the story details so users don’t need to scroll down to the metadata table.
=> UI: add elapsed time to story details

newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts
Fix the date range display by removing the end date query param only when it matches the default range’s end date.
=> UI: fix date range display

newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/ItemData.tsx
I think this used to work, but was lost along the way somewhere. The item fetch endpoint will include a highlight if the text query is included, but it's currently not being included so is not being returned. Update the client to include the current text query (if there is one) in the request, so the highlight can be generated, returned and displayed by existing code.
=> restore highlights in wire detail by sending the q param on item fetch

newswires/client/src/SearchSummary.tsx
Remove search filter only when clicking on a search summary badge icon.
=> UI: fix search summary badge

newswires/app/conf/SearchBuckets.scala, newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/SearchSummary.tsx, newswires/client/src/SideNav.tsx, newswires/client/src/sharedTypes.ts, newswires/client/src/urlState.ts, newswires/test/db/FingerpostWireEntrySpec.scala
- Rename `Buckets` to `Presets`
- Remove specific buckets and only keep `World`
- Fix all world bucket
=> UI: update buckets

ingestion-lambda/package.json, ingestion-lambda/src/categoryCodes.test.ts, ingestion-lambda/src/categoryCodes.ts, ingestion-lambda/src/handler.ts, ingestion-lambda/src/ukPlaces.ts, newswires/app/conf/SearchPresets.scala, package-lock.json
Add minor agencies world: since minor agencies don’t have category codes, infer the UK region category code using known UK locations, and exclude the category code from the search preset.
=> Minor agencies world

newswires/client/src/WireDetail.tsx, newswires/client/src/sharedTypes.ts, newswires/client/src/suppliers.ts
Add abstract to the story details for AP stories.
=> UI: add abstract for AP stories

newswires/client/src/App.tsx, newswires/client/src/SearchSummary.tsx, newswires/client/src/SideNav.tsx, newswires/client/src/Tooltip.tsx
- Add ticker buttons next to the supplier filter in the side nav (shows on hover)
- Add a ticker button in the search summary (include a tooltip)
- Add custom tooltip (as the Elastic UI tooltip doesn't work)
- Replace the ticker button in the search summary with a beacon in ticker windows (the beacon becomes red when the app goes offline)
Supplier filter:
Hover state:
Search summary:
Ticker window:
Offline ticker window:
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technolo …
=> UI: move ticker button

cdk/bin/cdk.ts
Enable GuCDK's default monitoring EC2 configuration for the PROD server.
=> Enable monitoring in PROD

ingestion-lambda/src/categoryCodes.test.ts, ingestion-lambda/src/categoryCodes.ts, ingestion-lambda/src/handler.ts, newswires/app/conf/SearchPresets.scala, newswires/client/src/category-code-lookup-tables.ts, newswires/client/src/sharedTypes.ts, shared/types.ts
Ingest destination codes for Reuters stories. Reuters destination codes are saved as custom cat codes and used for routing stories (e.g., RWS, which stands for Reuters World Story).
=> Update Reuters World preset

newswires/client/.storybook/preview-head.html, newswires/client/src/Item.stories.tsx, newswires/client/src/SearchBox.stories.tsx
A couple of recent PRs introduced dependencies which hadn't been added to the storybook config.
=> Add window config and telemetry provider to stories

newswires/client/src/WireDetail.tsx
Copy & paste was often bringing in visually hidden fields, and list styling, which is not ideal.
On reflection, there's no great need for the byline, body text and abstract to be rendered as part of the description list, because they're the main content of the item. So a simple solution is to pull them out of it.
|Before|After|
|-|-|
|<img width="798" alt="image" src="https://github.com/user-attachments/assets/6779d7a8-2634-4412-9ea4-fd910cc3d970" />|<img width="796" alt="image" src="https://github.com/user-attachments/assets/5d90ed21-e90c-40ac-9b71-1921bfb1852b" />|
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/pe …
=> Fix copy & paste of body text

newswires/client/src/Feed.tsx, newswires/client/src/SearchSummary.tsx
Reduce spacing at the top of ticker windows to allow more space for the news feed.
Before:
After:
=> UI: improve ticker spacing

newswires/client/src/App.tsx, newswires/client/src/SettingsMenu.tsx, newswires/client/src/WireItemList.tsx, newswires/client/src/context/UserSettingsContext.tsx, newswires/client/src/icons.ts, newswires/client/src/main.tsx, newswires/client/src/suppliers.ts
- Add a `UserSettingsContextProvider` with a `showSecondaryFeedContent` setting.
- Change the layout of the feed cards depending on that setting.
- A couple of other tweaks to the card layouts to standardise the grid sizes and reduce vertical spacing when either title or content wraps.
A few people have asked for a more compact view, we should check to see if this works better for them.
Default view, before and after:
---
Default and compact views in this branch: …
=> Add toggle for 'compact view' (hide subheadings from feed)

newswires/client/src/App.tsx
- Reduce the height of alert messages. 
Restricted search:
Offline:
=> UI: make Alert messages smaller

ingestion-lambda/src/suppliers.ts
Seems like one of the source feeds in Fingerpost land has been renamed, so we need to update the mapping.
=> Add APAPIUS to sourcefeed-supplier mapping for AP

newswires/client/src/SearchSummary.tsx, newswires/client/src/dateHelpers.ts
- We don't generally show other filters when they're set to the default value, and users seem to value there being less metadata in the view where possible, especially in ticker view. 
- Also, you can't actually remove this filter (except by setting a different value) so having the dismissible badge at the top is a bit misleading.
|Before|After|
|-|-|
|<img width="393" alt="image" src="https://github.com/user-attachments/assets/86c60a11-8a05-470e-9b18-06489521d355" />|<img width="395" alt="image" src="https://github.com/user-attachments/assets/efeeec27-ecb1-4524-8d16-0be000abbc61" />| …
=> Don't show date info in search summary if it's the same as the default

newswires/client/src/WireItemList.tsx
Fix feed item line break.
Before:
After:
=> UI: fix feed item line break

newswires/client/src/WireItemList.tsx
Override the `line-break: anywhere` on wire item list for the date component, because it was being split in an unreadable way on the 'compact' view. (See screenshots below)
Before:
After:
=> Don't allow timestamps to line break anywhere

newswires/app/conf/SearchPresets.scala
Some stories belong the Reuters Business and Reuters World, exclude those stories from the World preset.
=> Exclude business stories from Ru World

newswires/client/src/App.tsx, newswires/client/src/ResizableContainer.tsx, newswires/client/src/SettingsMenu.tsx, newswires/client/src/context/UserSettingsContext.tsx
- Refactor the resizable panels to make it easier to pass a direction prop (horizontal/vertical)
- Add a new setting to allow users to toggle panel direction
- Also save the preferred proportions of the two panels in localstorage, for each orientation, so that it will re-open in the same layout
- On small screens:
- For standard view, still open items separate from the feed (no split)
- For ticker view, always open items in a split below the feed, regardless of user preference for direction
|Horizontal|Vertical|
|-|-|
|**Desktop breakpoints**||
|<img width="1916" alt="image" src="https://github.com/user-attachments/assets/6ceaff9b-bebc-49c7-8354-45b565371001" />|<img width="1916" alt="image" src="https://github.com/user-attachments/assets/42dd936f-f2a4-48b4-9e79-932912c13e70" />| …
=> Add horizontal/vertical split toggle

newswires/client/src/App.tsx, newswires/client/src/DatePicker.tsx, newswires/client/src/icons.ts
1. Reduce the horizontal space needed for the header elements when rendering in smaller breakpoints:
- Icon-only button for the new ticker button
- Icon-only visual rendering of the beta badge
2. Use 'compact' mode for the date picker (not related to the header changes, but felt like a small enough change that it was reasonable to bundle in here)
---
New layout on smaller screens:
---
Comparison of non-compact (left) vs. proposed compact (right) versions of the date picker:
=> Fix: header for smaller screens

newswires/app/conf/SearchPresets.scala
Exclude `MCCL:OEC` from Reuters World.
=> Exclude economic news from Reuters World

newswires/client/src/WireItemList.tsx
Insert a hyphen whenever a word is split across a line break in the story list.
=> UI: add hyphens to word breaks on story list items

ingestion-lambda/src/ukPlaces.ts
Update minor agencies UK:
- Add Glastonbury to UK places.
=> Add Glastonbury to UK places

newswires/client/src/SearchSummary.tsx
We haven't got great support for managing category code searches yet, but this would be helpful for development, and if any other users _do_ manage to add an exclusion here then it's good to have it represented in the search summary.
When we do something more 'proper' for category codes we can also come up with better UX than just putting '(NOT)' in front of exclusions, but should be sufficient for the time being?
=> Show badges for categoryCodeExcl in search summary

newswires/client/src/Item.tsx
This is something a couple of people have asked for, and it feels like sensible behaviour.
=> Scroll to top of item when new item is opened

newswires/client/src/openTicker.ts
#279 introduced a regression where the `isOpenAsTicker` function was checking whether the page was a feed view. But the item view needs to be informed by whether the window's open as a ticker or not, too.
=> Item view also needs to know about ticker status

newswires/app/conf/SearchPresets.scala
- Remove business channel filter on Reuters world search preset.
=> Backend: update Reuters World preset

newswires/client/src/DatePicker.tsx, newswires/client/src/dateHelpers.ts
Add date search presets:
- Last 3 days
- Last 1 week
Date picker:
Search summary:
=> UI: add date search presets

newswires/app/conf/SearchPresets.scala, newswires/client/src/WireItemList.tsx
- Remove Reuters from UK preset
- Add slug to PA story list items
- Replace `<br />` with a space in body text preview for story list items
=> Improve UK preset

newswires/client/src/App.tsx, newswires/client/src/DatePicker.tsx, newswires/client/src/Disclosure.stories.tsx, newswires/client/src/SearchBox.tsx, newswires/client/src/SettingsMenu.tsx, newswires/client/src/context/KeyboardShortcutsContext.tsx, newswires/client/src/context/SearchContext.tsx, newswires/client/src/main.tsx
Un-revert #287 
The original PR was reverted because the logic I'd added to prevent keypresses from propagating to the global shortcut handler when keyboard-operable components were active, was not working properly.
This PR re-instates the global shortcut handler, whilst adding a more robust process to stop propagation of shortcut keypresses on certain components. I've also identified a couple of other components where we don't want to propagate shortcut keys (i.e. the date picker and the settings menu, where arrow keys and/or the escape key are used within the components themselves). …
=> Re-raise hotkey fixes

newswires/client/src/App.tsx, newswires/client/src/Feed.tsx, newswires/client/src/ResizableContainer.tsx, newswires/client/src/ScrollToTopButton.tsx, newswires/client/src/context/SearchReducer.ts, newswires/client/src/icons.ts
Add jump to top button:
- Accumulate counts of newly loaded stories and reset when scrolling up
- Show/hide the button based on scroll offset
- Recalculate position on show, scroll, or resize
Large screen feed only:
Large screen with opened story:
Large screen with story opened below feed:
Small screen feed only:
Ticker screen feed only:
Ticker screen feed wit story opened below feed:
-   [ ] …
=> UI: add jump to top button

newswires/client/src/Feed.tsx, newswires/client/src/ResizableContainer.tsx, newswires/client/src/ScrollToTopButton.tsx
Fix the Scroll-to-top button position when toggling from 'show item below' to 'show item next to feed'.
Rogue button example:
=> UI: fix back to top button position bug

newswires/client/.eslintrc.cjs, newswires/client/.storybook/preview-head.html, newswires/client/src/SearchSummary.tsx, newswires/client/src/SideNav.tsx, newswires/client/src/app-configuration.ts, newswires/client/src/context/SearchContext.tsx, newswires/client/src/windowConfigType.ts
- Fix a bug whereby dismissing a category code search badge wasn't removing the code from the search config.
- As part of addressing this, refactor the SearchSummary component to add a bit more type safety, to hopefully reduce the chance of this happening again, if new badges are created, or old ones are renamed. …
=> Fix search badge toggle behaviour

newswires/client/src/SideNav.tsx, newswires/client/src/suppliers.ts
Shorter label is more consistent with other labels, and we agreed as a team that 'minor' should be sufficiently clear to users.
=> 'Minor agencies' becomes 'minor'

newswires/client/src/TelemetryPixel.tsx, newswires/client/src/main.tsx, newswires/client/src/telemetry.ts
Adds the [tracking pixel](https://github.com/guardian/editorial-tools-user-telemetry-service?tab=readme-ov-file#tracking-pixel) that's being used as part of the tools audit. 
**nb.** This telemetry does include some user information, but this mechanism has been reviewed recently with Data Privacy as part of the tools audit. Our intention in adding it is only to understand how many distinct users are using the service, using a mechanism that provides parity between this service and the legacy `editorial-wires` service.
- …
=> Add telemetry tracking pixel

newswires/client/src/SideNav.tsx
Currently the 'open new ticker window' secondary action button is in the tab order of the page, but isn't visible when the button is focused. Rather, it's only visible on hover.
This branch makes it visible whenever the parent button is focused, which matches the current hover behaviour. …
=> Show 'open new ticker' secondary actions when focus is within parent button

newswires/client/src/App.tsx, newswires/client/src/SearchBox.tsx
Fix issue with the clear button on the search box.
Before:
After:
=> UI: fix clear button on search box

.scala-steward.conf
Currently scala-steward is only finding the db project... try and nudge it in the right direction
=> Add scala steward conf to find all subprojects

newswires/app/conf/SearchPresets.scala, newswires/client/src/SearchSummary.tsx, newswires/client/src/SideNav.tsx, newswires/client/src/category-code-lookup-tables.ts
Add UK sport search preset, only include sport news stories (exclude fixtures and results).
=> Add UK sport preset

newswires/client/src/urlState.ts
Issue:
The home URL does not update when the search query changes.
Update:
Update the home URL in the same way as the feed URL when converting the URL to a config.
=> UI: handle home URL when converting URL to config

newswires/client/src/DatePicker.tsx, newswires/client/src/Feed.tsx
Make the story list top section layout responsive on large screens.
Before:
After:
=> UI: update story list top section layout

cleanup-lambda/src/handler.ts, ingestion-lambda/src/handler.ts, jest.config.js, newswires/client/src/ComposerConnection.tsx, newswires/client/src/ItemData.tsx, newswires/client/src/context/SearchContext.tsx, newswires/client/src/context/SearchReducer.ts, newswires/client/src/context/fetchResults.ts, newswires/client/src/context/localStorage.tsx, poller-lambdas/src/index.ts, poller-lambdas/src/pollers/reuters/auth.ts, shared/getErrorMessage.test.ts, shared/getErrorMessage.ts
There are a number of places where we try to pull a useful message out of an `Error` (or, more accurately, something that's been thrown). We're doing it in slightly different ways in different places.
There's a [blog post about extracting error messages in TypeScript](https://kentcdodds.com/blog/get-a-catch-block-error-message-with-typescript) which seems to cover most of the possible cases pretty well, so it feels worth adding as a helper function and just using that when needed.
=> Refactor TS error handling

newswires/client/src/App.tsx, newswires/client/src/ResizableContainer.tsx, newswires/client/src/context/SearchContext.tsx, newswires/client/src/context/UserSettingsContext.tsx, newswires/client/src/context/localStorage.tsx, newswires/client/src/send-to-composer.ts, newswires/client/src/sharedTypes.ts, newswires/client/src/telemetry.ts, newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts, poller-lambdas/src/pollers/reuters/auth.ts, poller-lambdas/src/pollers/reuters/reutersPoller.ts
Starts importing zod from `zod/v4` instead of `zod`. It doesn't require a package.json change, because v4 is exported from >=v3.25:
> To simplify the migration process both for users and Zod's ecosystem of associated libraries, Zod 4 will initially published alongside Zod 3 as part of the zod@3.25 release. Despite the version number, it is considered stable and ready for production use. ([zod docs](https://zod.dev/v4))
As we can see above, v4 is stable so it seems reasonable to upgrade. More specifically I found myself being about to add some new code which uses a now-deprecated zod v3 function, so thought it might be a good time to upgrade now to avoid starting using a function that we know we're going to have to replace. …
=> Start using zod v4

newswires/app/db/FingerpostWireEntry.scala, newswires/client/src/sharedTypes.ts, shared/types.ts
- Change the ingestion lambda and client-side types to be 'looseObjects', so that they will validate the fields they are expecting, but (if validation passes) just pass through any unrecognised fields.
- Update the API to send through the new `composerCompatible` and `dataformat` fields. **nb.** this required temporarily removing the 'language' and 'location' fields, because we hit the 22 field limit after which Play's serialisation magic breaks. These two fields aren't currently being used by the client, but I've created a ticket to find a better solution to the 22 field limit and to restore these fields when we've done so. …
=> Preserve unrecognised fields in ingestion, and add dataformatting fields to API

newswires/client/src/App.tsx, newswires/client/src/Item.stories.tsx, newswires/client/src/Item.tsx, newswires/client/src/WireItemList.tsx, newswires/client/src/context/KeyboardShortcutsContext.tsx, newswires/client/src/context/SearchContext.tsx, newswires/client/src/context/SearchReducer.test.ts, newswires/client/src/context/SearchReducer.ts
Load more stories when the 'Next Story' button is clicked on the last story in the list.
=> UI: improve next story button

newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts
We already do this for the end date and other defaults.
=> Remove start date from url if it matches the default start value

newswires/conf/routes
We've had multiple reports of users receiving error messages because the CSRF token in their window has expired when they send an item to Composer, and the composer id callback fails.
This is a confusing user experience, and also means that we can't connect the wire entry with the Composer article.
- Fewer user-facing errors
- We're able to connect wires to Composer articles, which is useful for editorial workflows
PUT requests to this endpoint do trigger a write to the database, but the state change is restricted by the endpoint logic to updating the composer id and the id of the user who sent the wire to Composer.
We've checked that CORS is enabled. And we've documented the reason for the exemption inline in the code, alongside a prompt to reconsider the exemption in the future if …
=> Disable CSRF checks for the composer id callback path

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/__snapshots__/whole-stack.test.ts.snap, cdk/lib/newswires.ts, ingestion-lambda/src/handler.ts
- Export ingestion lambda arn as a cloudformation output, to allow for SES integration in followup PR: https://github.com/guardian/editorial-wires/pull/180
- If the ingestion lambda is invoked with an SES message, just log the input and exit (actual handling logic to be added in a followup PR) …
=> Prepare for email integration

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/__snapshots__/whole-stack.test.ts.snap, cdk/lib/newswires.ts
We don't keep application logs for all that long, so it seems reasonable to bring the cloudfront logs retention more into line too.
Also, the prompt for this particular change is that we need to make a non-trivial change to the Cloudformation template in order to trigger creation of the Cfn output added in #358  …
=> Lifetime for cloudfront logs more comparable to our other logs

newswires/client/src/WireDetail.tsx
Testing out the idea of having a button that will copy the headline and url for an item:
1. Restructure wire item detail header to be more semantic, and separate out the pieces that sit on different lines, so as to enable (2)
2. Add a copy button for the headline and url:
- 'text/plain': `${headlineText}\n${fullUrl}`
- 'text/html': `<a href="${fullUrl}">${headlineText}</a>`
=> Add 'copy headline and URL' button

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/__snapshots__/whole-stack.test.ts.snap, cdk/lib/newswires.ts
As part of the 'sport.copy' email integration, we need to have an S3 bucket where SES can put incoming messages.
=> Create bucket for incoming email copy

newswires/app/conf/SearchPresets.scala, newswires/app/controllers/QueryController.scala, newswires/app/db/FingerpostWireEntry.scala, newswires/app/models/Dataformat.scala, newswires/app/models/FingerpostWire.scala, newswires/app/models/FingerpostWireSubjects.scala, newswires/app/models/QueryParams.scala, newswires/app/models/QueryResponse.scala, newswires/app/models/SearchParams.scala, newswires/build.sbt, newswires/test/db/FingerpostWireEntrySpec.scala, newswires/test/helpers/models.scala, newswires/test/models/FingerpostWireSpec.scala, newswires/test/models/FingerpostWireSubjectsSpec.scala, newswires/test/models/FingerpostWireSubjectsTest.scala, newswires/test/models/FingerpostWireTest.scala
This swaps out the json serialising and deserialsing library from play json to using the circe library. This is because the `FingerpostWire` case class is already at 21 fields and adding an extra field causes the play library to break. Since we may want to add new fields in the future, using the circe library means we would not hit the same 22 field constraint. 
I've run it locally at tested that the U.I still works at that filtering yields the same results locally as it does in the code environment. 
-   [ ] [Colour …
=> Implement a different json library

scripts/setup
When using the "overwrite" option in the setup script, it's currently just appending the values to the existing config file. This should work as the config lib reads top-to-bottom, so later values will replace earlier ones in memory, but it's still nice to clean up as we go.
Use the overwrite option a few times, you should end with a config file that's a little bit neater.
=> fix setup overwrite_config to fully overwrite

.github/workflows/ci.yaml, cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/__snapshots__/riffraff.test.ts.snap, cdk/lib/__snapshots__/whole-stack.test.ts.snap, cdk/lib/newswires.ts, email-filter-lambda/package.json, email-filter-lambda/src/findVerificationFailures.test.ts, email-filter-lambda/src/findVerificationFailures.ts, email-filter-lambda/src/handler.ts, email-filter-lambda/tsconfig.json, jest.config.js, package-lock.json, package.json
Add new SES receipt rule that invokes a lambda. The lambda itself just checks some of the metadata from AWS's scan of the email, and logs the result. Once we've checked that it operates as expected in PROD, we can get it to reject messages which fail these checks (see this [example of spam filtering from the docs](https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-lambda-example-functions.html)).
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visua …
=> Add logging-only email filter lambda

cleanup-lambda/src/handler.ts, ingestion-lambda/src/categoryCodes.test.ts, ingestion-lambda/src/handler.test.ts, ingestion-lambda/src/handler.ts, ingestion-lambda/src/processContentObject.test.ts, ingestion-lambda/src/processContentObject.ts, shared/rds.ts
- Extract the main wire item processing functionality from the body of the handler, and put it in `processContentObject.ts` (along with the various supporting functions)
- Slightly refactor the db connection export from `rds.ts` to make it easier to mock
- Add tests to cover the main branches of the ingestion-lambda handler. Move pre-existing content processing tests from `handler.test.ts` to `processContentObject.test.ts`
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-techno …
=> Refactor db utils and content processing; add ingestion handler test

newswires/app/controllers/QueryController.scala, newswires/app/db/ToolLink.scala
Oversight in #382  - I forgot to come back and fix where I'd hardcoded composer's CODE domain on insertion to the new database 🤦 
Come back and do it quickly, hopefully before anyone notices.
Hard to see the fix on CODE, since it already was storing the right URL... At most checking that it hasn't caused a regression should be enough.
=> Need to vary the composer host to match the stage!

cdk/lib/__snapshots__/newswires.test.ts.snap, cdk/lib/__snapshots__/whole-stack.test.ts.snap, cdk/lib/newswires.ts, ingestion-lambda/src/handler.test.ts
Adds a metric filter alarm on ingestion failures, so we should be able to spot when things go wrong pretty quickly
=> Ingestion failed alarm

newswires/app/db/FingerpostWireEntry.scala, newswires/test/db/FingerpostWireEntrySpec.scala
- Refactors the building of where clauses:
- `sqls.joinWithOr()` works fine with no arguments (returns an empty sqls clause) or just one argument (it returns it unmodified) so we don't need to do so many checks to see whether we have 0, 1 or >1 clauses before passing to this method.
- Always add a 'where' clause, with 'true' as the fallback/default if there are no other clauses in play. (So we can add the 'where' part just once, when we're constructing the final query.)
- Add the `beforeId`/`sinceId` clauses in at the top level of the where clause:
- Previously, they were being added to each of the sub-clauses, i.e. the custom search clause and the saved search/presets clause.
- But because these sub-clauses are being joined with 'AND', we can just add the before/since clauses at the top …
=> Refactor where clause builder, fixing beforeId/sinceId handling

newswires/client/src/WireDetail.tsx, newswires/client/src/app-configuration.ts, newswires/client/src/context/SearchContext.tsx, newswires/client/src/context/fetchResults.test.ts, newswires/client/src/context/fetchResults.ts, newswires/client/src/sharedTypes.ts, newswires/client/src/suppliers.ts, newswires/client/src/urlState.test.ts, newswires/client/src/urlState.ts, newswires/conf/routes
Add `/dotcopy` and `/dotcopy/item/:id` routes to the app, to serve versions of the feed and item views that just pull in dotcopy items.
This branch isn't trying to integrate the dotcopy view with the regular feed view in any kind of user-friendly way. Rather, it's just getting the rendering and routing logic in place. UX for navigation etc. will come later.
I'm also hoping to do some more refactors to the client-side routing in general, but I didn't want to block this change behind that, and I don't think that the additional routing logic introduced here will make the future refactor significantly more difficult. …
=> Add dotcopy view to UI

newswires/client/src/Item.stories.tsx, newswires/client/src/WireItemList.tsx, newswires/client/src/context/transformQueryResponse.test.ts, newswires/client/src/context/transformQueryResponse.ts, newswires/client/src/sharedTypes.ts, newswires/client/src/tests/fixtures/wireData.ts
We've started getting the headlines through from Fip for items with data formatting, but the headline includes the slug. So we shouldn't add the slug to the headline in the feed view, for items with data formatting.
=> Deduplicate slug in feed for items with data formatting

newswires/app/conf/SearchPresets.scala
This modifies the world preset to include stories with "General News" that are in the world category. 
=> Add a general world category
